Completed task
Vedroid/jv-mate-multithreading pull request #1
Opened 2021-02-22 13:28 UTC by Vedroid

2021-02-22 13:34 UTC, YuraMitriakhin approved these changes
good job

2021-02-22 16:07 UTC, Sofasmile requested changes

2021-02-22 16:07 UTC, Sofasmile commented on src/main/java/ua/vedroid/multithreading/Counter.java
> +    public void incrementNum() {
```suggestion
    public int incrementNumber() {
```

2021-02-22 16:07 UTC, Sofasmile commented on src/main/java/ua/vedroid/multithreading/ThreadA.java
> +            counter.incrementNum();
```suggestion
            int newValue = counter.incrementNum();
```

2021-02-22 16:07 UTC, Sofasmile commented on src/main/java/ua/vedroid/multithreading/ThreadA.java
> +            log.info(threadName + " - " + counter.getNum());
```suggestion
            log.info(threadName + " - " + newValue);
```

2021-02-23 07:53 UTC, Sofasmile approved these changes

2021-02-23 11:09 UTC, merged